baseURL = 'https://levasseurelec.com'
languageCode = 'en-us'
title = 'Levasseur Electric'
theme = "hugo-hero-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"
    
[params]
  google_analytics_id=""

  [params.logo]
    mobile = "images/levasseureelecLogo-prop.svg"
    mobile_height = "36px"
    mobile_width = "36px"
    desktop = "images/levasseureelecLogo-prop.svg"
    desktop_height = "29px"
    desktop_width = "217px"
    alt = "Levasseur Electric"

  [params.homepage_meta_tags]
    meta_description = ""
    meta_og_title = ""
    meta_og_type = "website"
    meta_og_url = ""
    meta_og_image = ""
    meta_og_description = ""
    meta_twitter_card = "summary"
    meta_twitter_site = ""
    meta_twitter_creator = ""

[[menu.main]]
	name = "Services"
	url = "/services/"
    weight = 1

[[menu.main]]
    name = "Work"
    url = "/work/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[[menu.main]]
    name = "History"
    url = "/history/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
